# NumPy

- Open-source Python library
- Fundamental package for scientific computing   
- Multi-dimensional array
    - Matrix: dimension 2
    - Vector: dimension 1
    - Scalar: dimension 0
 

### Motivation example

In [1]:
# assume you are given the two matrices
m1 = [[12,7,3], 
      [4 ,5,6], 
      [7 ,8,9]] 

m2 = [[5,8,1], 
      [6,7,3], 
      [4,5,9]] 

# to compute m1 x m2, you need the following code

# we know m1 and m2 have the size (3,3), 
# so the result matrix also has the size (3,3)
# (3,3) x (3,3) => (3,3)
# we thus initialize the result matrix with all 0 values
res = [[0,0,0], 
       [0,0,0], 
       [0,0,0]]

# here we follow the matrix multiplication formula
for i in range(len(m1)): 
    for j in range(len(m2[0])): 
        for k in range(len(m2)): 
  
            # resulted matrix 
            res[i][j] += m1[i][k] * m2[k][j]

print(res)

[[114, 160, 60], [74, 97, 73], [119, 157, 112]]


In [2]:
# Import NumPy 
import numpy as np

m1 = np.array([[12,7,3], 
               [4 ,5,6], 
               [7 ,8,9]])

m2 = np.array([[5,8,1], 
               [6,7,3], 
               [4,5,9]]) 

res = m1.dot(m2)
print(res)

[[114 160  60]
 [ 74  97  73]
 [119 157 112]]


### Multi-dimensional arrays: `ndarray`


### Create ndarray from existing data

In [5]:
# We can initalize arrays from existing data by calling the function np.array
print("Initialize arrays with different dimensions\n")

# initialize an array (1D array)
print("initialize a vector / 1D-array")
arr1 = np.array([1,2,3,4,5,6])
print("arr1 = np.array([1,2,3,4,5,6])")
print("arr1:", arr1) # print the array
print() # print an empty line

# 0D array
print("initialize a scalar / 0D-array")
arr0 = np.array(2)
print("arr0 = np.array(2)")
print("arr0:", arr0)
print() # print an empty line

# 2D array
print("initialize a matrix / 2D-array")
arr2 = np.array([[1,2,3], [4,5,6]]) 
print("arr2 = np.array([[1,2,3], [4,5,6]])")
print("arr2:")
print(arr2)
print() # print an empty line


print("------------\n")


print("Check the dimension of the arrays:")
print("arr0.ndim:", arr0.ndim) # check the dimension of the array
print("arr1.ndim:", arr1.ndim)
print("arr2.ndim:", arr2.ndim)

print()
print("Check the shape/size of the arrays:")
print("arr0.shape:", arr0.size) # total number of elements in the array
print("arr0.size:", arr0.size) 
print("arr1.shape:", arr1.shape) # number of elements in each dimension
print("arr1.size:", arr1.size)
print("arr2.shape:", arr2.shape) # the shape of the matrix
print("arr2.size:", arr2.size) # count the number of elements in the matrix

print("\n------------\n")

a = np.array([1,2,3,4,5,6])
b = np.array([[1,2,3,4,5,6]])
c = np.array([[1], [2], [3], [4], [5], [6]])
print("Consider the following three arrays:")
print("a =", a)
print("b =", b)
print("c =")
print(c)
print()

print("Although they contain the same values, they mean different data structures in NumPy.")
print("a is a vector with only one dimension")
print("a.ndim:", a.ndim)
print("a.shape:", a.shape)
print()
print("b and c are matrices with two dimensions")
print("where b has one row and six columns, and c has six rows and one column:")
print("b.ndim:", b.ndim, ", c.ndim:", c.ndim)
print("b.shape:", b.shape, ", c.shape", c.shape)


Initialize arrays with different dimensions

initialize a vector / 1D-array
arr1 = np.array([1,2,3,4,5,6])
arr1: [1 2 3 4 5 5]

initialize a scalar / 0D-array
arr0 = np.array(2)
arr0: 2

initialize a matrix / 2D-array
arr2 = np.array([[1,2,3], [4,5,6]])
arr2:
[[1 2 3]
 [4 5 6]]

------------

Check the dimension of the arrays:
arr0.ndim: 0
arr1.ndim: 1
arr2.ndim: 2

Check the shape/size of the arrays:
arr0.shape: 1
arr0.size: 1
arr1.shape: (6,)
arr1.size: 6
arr2.shape: (2, 3)
arr2.size: 6

------------

Consider the following three arrays:
a = [1 2 3 4 5 6]
b = [[1 2 3 4 5 6]]
c =
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

Although they contain the same values, they mean different data structures in NumPy.
a is a vector with only one dimension
a.ndim: 1
a.shape: (6,)

b and c are matrices with two dimensions
where b has one row and six columns, and c has six rows and one column:
b.ndim: 2 , c.ndim: 2
b.shape: (1, 6) , c.shape (6, 1)


### Built-in functions for creating ndarrays 

In [9]:
# functions for creating arrays

# create arrays of all zero
zeros = np.zeros((2,3)) # create a 2x3 matrix of all 0
print("Create a 2x3 matrix of 0: ")
print("np.zeros((2,3)):")
print(zeros)
print()

# create arrays of all one
ones = np.ones((6,1)) # create a 6,1 matrix of all 1
print("Create a 6x1 matrix of 1: ")
print("np.ones((6,1)):")
print(ones)
print()

# create identity matrices 
# An identity matrix is a square matrix that has 1's along the main diagonal 
# and 0's for all other entries.
eye = np.eye(5) # identity matrix with shape 5x5
print("Create a 5x5 identity matrix:")
print("np.eye(5):")
print(eye)
print("Shape of the identity matrix:", eye.shape)
print()


# create arrays with random values in [0,1)
print("Create a 3x2 matrix with random values in [0,1):")
r = np.random.random((3,2)) # create an array with random values from 0 to 1
print("np.random.random((3,2)):")
print(r)
print()


# create arrays of the input value
print("Create a 2x2 matrix of 4:")
print("np.full((2,2), 4):")
c = np.full((2,2), 4) 
print(c)
print("np.zeros and np.ones are instances of np.full")
print("E.g. np.zeros((2,3)) = np.full((2,3), 0)")


Create a 2x3 matrix of 0: 
np.zeros((2,3)):
[[0. 0. 0.]
 [0. 0. 0.]]

Create a 6x1 matrix of 1: 
np.ones((6,1)):
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

Create a 5x5 identity matrix:
np.eye(5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Shape of the identity matrix: (5, 5)

Create a 3x2 matrix with random values in [0,1):
np.random.random((3,2)):
[[0.02023852 0.82896821]
 [0.7031192  0.47915008]
 [0.11724635 0.29508309]]

Create a 2x2 matrix of 4:
np.full((2,2), 4):
[[4 4]
 [4 4]]
np.zeros and np.ones are instances of np.full
E.g. np.zeros((2,3)) = np.full((2,3), 0)


### Indexing and slicing ndarrays

In [10]:
# indexing 

# create a 3x4 matrix
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print("Create the matrix :")
print(m)
print()

# access an element by indeces
print("Access the element at the second row and first column:")
# Python follows zero-based numbering, 
# i.e., the first element is assigned index 0 rather 1
print("m[1,0]:", m[1,0]) # The first number refers to the index of the row 
                           # while the second number refers to that of the column")
print()
print("------------\n")

# slicing

# access multiple elements
print("Use slicing to select a range of elements\n")

# [1:5] => [1,2,3,4]

print("Extract elements that are in the first two rows and the 2nd and 3rd columns:")
print("m[:2,1:3]:") 
print(m[:2,1:3])
print("the slicing 1:3 means [1,2], i.e., second and third. Note 3 is excluded.")
print("the slicing :2 is equivalent to 0:2, which means indeces [0,1]")
print()
print("The extracted sub-matrix has the shape 2x2:")
print("m[:2,1:3].shape:", m[:2,1:3].shape)


print("\n----------\n")

print("Extract the second row of the matrix:")
print(": means taking all elements of the dimension")
print("m[1,:]:", m[1,:]) # : means taking all elements of the dimension
print("m[1,:].shape:", m[1,:].shape)

print()

print("Extract the first column of the matrix a")
print("m[:,0]:", m[:,0]) # 
print("m[:,0].shape:", m[:,0].shape)

print()

print("Note mixing integer indexing with slices yields a vector rather than a matrix.")
print("m[:,0].shape:", m[:,0].shape)
print("Use only slices yields a matrix:")
print("m[:,0:1].shape:", m[:,0:1].shape)


Create the matrix :
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Access the element at the second row and first column:
m[1,0]: 4

------------

Use slicing to select a range of elements

Extract elements that are in the first two rows and the 2nd and 3rd columns:
m[:2,1:3]:
[[2 3]
 [5 6]]
the slicing 1:3 means [1,2], i.e., second and third. Note 3 is excluded.
the slicing :2 is equivalent to 0:2, which means indeces [0,1]

The extracted sub-matrix has the shape 2x2:
m[:2,1:3].shape: (2, 2)

----------

Extract the second row of the matrix:
: means taking all elements of the dimension
m[1,:]: [4 5 6]
m[1,:].shape: (3,)

Extract the first column of the matrix a
m[:,0]: [ 1  4  7 10]
m[:,0].shape: (4,)

Note mixing integer indexing with slices yields a vector rather than a matrix.
m[:,0].shape: (4,)
Use only slices yields a matrix:
m[:,0:1].shape: (4, 1)


#### **Exercise**: Use array slicing to split a dataset to training data and test data

In [11]:
# load the sample dataset to the variable X
X = np.loadtxt(open("./california_housing_train.csv", "rb"), delimiter=",", skiprows=1) 
# X = np.loadtxt(open("/content/sample_data/california_housing_train.csv", "rb"), delimiter=",", skiprows=1) # for Google Colab

print("X.shape:", X.shape)
print("The matrix X has {} rows and {} columns, i.e., {} records and {} attributes".format(X.shape[0], X.shape[1], X.shape[0], X.shape[1]))

print("\n-----------------\n")

# We want to use the first 80% rows as training data, and the remaining 20% as test data
# How do we split the data?
print("Split X into X_train and X_test\n")

# compute the number of rows in the training data
train_size = int(X.shape[0] * 0.8) # cast the number to an integer
print("Training data size:", train_size)

X_train = X[:train_size, :] # the first 'train_size' rows of X
X_test = X[train_size:] # rows after the train_size th row

print("X_train.shape:", X_train.shape)
print("X_test.shape:", X_test.shape)


X.shape: (17000, 9)
The matrix X has 17000 rows and 9 columns, i.e., 17000 records and 9 attributes

-----------------

Split X into X_train and X_test

Training data size: 13600
X_train.shape: (13600, 9)
X_test.shape: (3400, 9)


### Reshape ndarrays

In [12]:
# reshape the arrays

vec = np.array([1,2,3,4,5,6]) # init a vector
print("Create the vector vec =", vec)
print("vec.shape:", vec.shape)

print("\n-----------\n")

print("Convert a vector with six elements to a 2x3 matrix")

matrix = vec.reshape((2,3))
print("matrix = vec.reshape((2,3))")
print("matrix:")
print(matrix)
print("matrix.shape:", matrix.shape)
print()

print("Flatten the matrix to a vector")
vec2 = matrix.reshape(-1) # -1 means reshaping the array into a 1D array
print("vec2 = matrix.reshape(-1)")
print("vec2:")
print(vec2)
print("vec2.shape:", vec2.shape)


Create the vector vec = [1 2 3 4 5 6]
vec.shape: (6,)

-----------

Convert a vector with six elements to a 2x3 matrix
matrix = vec.reshape((2,3))
matrix:
[[1 2 3]
 [4 5 6]]
matrix.shape: (2, 3)

Flatten the matrix to a vector
vec2 = matrix.reshape(-1)
vec2:
[1 2 3 4 5 6]
vec2.shape: (6,)


### Iterate ndarrays

In [13]:
# create a 3x4 matrix
m = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
m = m.reshape((3,4)) # reshape the vector to a 3x4 matrix

print("create a 3x4 matrix m = ")
print(m)
print("m.shape:", m.shape)

print("\n-----------\n")
print("Iterate by rows using 'for row in m:'")
# for each row
for row in m:
  print(row)

print("\n-----------\n")
print("Iterate by columns using 'for row in m.T:'")

# we can iterate the rows of the transpose of the matrix
print()
print("m.T:")
print(m.T)
print()

# for each col
for col in m.T: # m.T means the transpose of m
  print(col)

print("where m.T means the transpose of m.")
print("note the transpose operation is not costly as it just changes the 'strides' of numpy arrays")

# note transpose operation is not costly as it just changes the 'strides' of array

print("\n-----------\n")
print("Iterate by elements using nested for loops:")
# for each element
for row in m:
  for elem in row:
    print(elem)

print("\n-----------\n")

print("Enumerate elements with indices:")
print("for i, elem in np.ndenumerate(m):")
# enumerate elements with index
for i, elem in np.ndenumerate(m):
  print(i, elem)




create a 3x4 matrix m = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
m.shape: (3, 4)

-----------

Iterate by rows using 'for row in m:'
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]

-----------

Iterate by columns using 'for row in m.T:'

m.T:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

[1 5 9]
[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
where m.T means the transpose of m.
note the transpose operation is not costly as it just changes the 'strides' of numpy arrays

-----------

Iterate by elements using nested for loops:
1
2
3
4
5
6
7
8
9
10
11
12

-----------

Enumerate elements with indices:
for i, elem in np.ndenumerate(m):
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12


### Concatenation of ndarrays

In [14]:
# consider the two vectors
print("Consider the two vectors")
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
print("vec1:", vec1)
print("vec2:", vec2)

print("\n---------------\n")

print("stack along rows / concatenate vectors horizontally")
print("np.hstack((vec1, vec2)):", np.hstack((vec1, vec2))) # stack along rows
print()

print("stack along columns / concatenate vectors vertically")
print("np.vstack((vec1, vec2)):")
print(np.vstack((vec1, vec2)))
print()


Consider the two vectors
vec1: [1 2 3]
vec2: [4 5 6]

---------------

stack along rows / concatenate vectors horizontally
np.hstack((vec1, vec2)): [1 2 3 4 5 6]

stack along columns / concatenate vectors vertically
np.vstack((vec1, vec2)):
[[1 2 3]
 [4 5 6]]



#### **Exercise**: Given a matrix, how to add a column of ones to the front of the matrix?

In [4]:
# init the given matrix
print("Consider the given matrix m:")
m = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)
print(m)
print("m.shape:", m.shape)

print("\n---------------\n")

print("Create the column of ones for the matrix")
vec = np.ones((m.shape[0], 1)) # m.shape[0] = the number of rows in m
print("vec = np.ones((m.shape[0], 1))")
print("vec:")
print(vec)
print()

print("Concatenate the column and the matrix")
print("m = np.hstack((vec, m))")
m = np.hstack((vec, m))
print("m:")
print(m)


Consider the given matrix m:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
m.shape: (3, 4)

---------------

Create the column of ones for the matrix
vec = np.ones((m.shape[0], 1))
vec:
[[1.]
 [1.]
 [1.]]

Concatenate the column and the matrix
m = np.hstack((vec, m))
m:
[[ 1.  1.  2.  3.  4.]
 [ 1.  5.  6.  7.  8.]
 [ 1.  9. 10. 11. 12.]]


### Datatypes

NumPy provides some extra data types, such as unsigned integers and datetime objects etc. 

When creating an array, numpy will try to guess the data type of the array, but you can also specify the type of the array. 



In [16]:
print("Create a vector by vec = np.array([1,2,3,4])")
print("NumPy will guess the data type of the array")
vec = np.array([1,2,3,4]) # numpy will guess the data type of the array
print("vec:", vec)
# check the data type of the array
print("vec.dtype:", vec.dtype)

print()
print("Consider another array with a floating number")
print("vec2 = np.array([1,2,3.0,4])")
vec2 = np.array([1,2,3.0,4])
print("vec2:", vec2)
print("vec2.dtype:", vec2.dtype)


# specify the data type when creating the array
# floor
print()
print("Specify the data type when creating the array")
print("vec3 = np.array([1.5, 2.5, 3.5, 4.5], dtype='int64')")
# numpy will cast the floating numbers to integers using floor
vec3 = np.array([1.5, 2.5, 3.5, 4.5], dtype='int64') 
print("vec3:", vec3) 
print("vec3.dtype:", vec3.dtype)


Create a vector by vec = np.array([1,2,3,4])
NumPy will guess the data type of the array
vec: [1 2 3 4]
vec.dtype: int32

Consider another array with a floating number
vec2 = np.array([1,2,3.0,4])
vec2: [1. 2. 3. 4.]
vec2.dtype: float64

Specify the data type when creating the array
vec3 = np.array([1.5, 2.5, 3.5, 4.5], dtype='int64')
vec3: [1 2 3 4]
vec3.dtype: int64


### Arithmetic operators



Basic operators operate elementwise on arrays. 

In [3]:
print("Consider the two 2x3 matrices:")
m1 = np.array([1,2,3,4,5,6]).reshape((2,3))
m2 = np.array([4,5,6,7,8,9]).reshape((2,3))
print("m1:")
print(m1)
print("m2:")
print(m2)

print("\n--------------\n")

print("Square root:")
print("np.sqrt(m1):")
print(np.sqrt(m1))

print("\n--------------------\n")

print("Sum of all values of m1")
print("np.sum(m1):", np.sum(m1)) # sum of all values
print()
print("Sum along rows")
print("np.sum(m1, axis=0):", np.sum(m1, axis=0)) # sum along rows
print()
print("Sum along columns")
print("np.sum(m1, axis=1):", np.sum(m1, axis=1)) # sum along cols


print("\n--------------\n")

print("Average:")
print("np.mean(m1) =", np.mean(m1))

print("\n--------------\n")

print("Average over the columns:")
print("np.mean(m1, axis=1) =", np.mean(m1, axis=1))

print("\n--------------\n")

print("Max:")
print("np.max(m1) =", np.max(m1))


print("\n--------------\n")

print("m1 + m2:")
print(m1 + m2)
print()

print("m1 - m2:")
print(m1 - m2)
print()

print("m1 * m2:")
print(m1 * m2)


Consider the two 2x3 matrices:
m1:
[[1 2 3]
 [4 5 6]]
m2:
[[4 5 6]
 [7 8 9]]

--------------

Square root:
np.sqrt(m1):
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]

--------------------

Sum of all values of m1
np.sum(m1): 21

Sum along rows
np.sum(m1, axis=0): [5 7 9]

Sum along columns
np.sum(m1, axis=1): [ 6 15]

--------------

Average:
np.mean(m1) = 3.5

--------------

Average over the columns:
np.mean(m1, axis=1) = [2. 5.]

--------------

Max:
np.max(m1) = 6

--------------

m1 + m2:
[[ 5  7  9]
 [11 13 15]]

m1 - m2:
[[-3 -3 -3]
 [-3 -3 -3]]

m1 * m2:
[[ 4 10 18]
 [28 40 54]]


### Matrix operators

In [18]:
# inner product of matrices / vectors

print("Consider the two vectors:")
# vectors
v = np.array([1,2,3,4,5,6])
w = np.array([6,7,8,9,10,11])
print("v:", v)
print("w:", w)
print()



# 1*6 + ...
print("Dot product")
print("v.dot(w):", v.dot(w)) # inner product of v and w
print("np.dot(v, w):", np.dot(v, w)) # same as above


print("\n--------------------\n")
print("Consider the two matrices:")
m1 = v.reshape((2,3))
m2 = w.reshape((3,2))
print("m1:")
print(m1)
print("m2:")
print(m2)
print()


print("Matrix multiplication")

# (2,3) x (3,2) => (2,2)
print("m1.shape:", m1.shape)
print("m2.shape:", m2.shape)
print("(2,3) x (3,2) => (2,2)")
print()

print("m1.dot(m2):")
print(m1.dot(m2))

print("m1 @ m2:")
print(m1 @ m2) # same as above 

print("m1.dot(m2).shape:", m1.dot(m2).shape)


print("\n--------------------\n")
print("Transpose of T")
# transpose
print("m1.T")
print(m1.T)
print("m1.T.shape:", m1.T.shape)



Consider the two vectors:
v: [1 2 3 4 5 6]
w: [ 6  7  8  9 10 11]

Dot product
v.dot(w): 196
np.dot(v, w): 196

--------------------

Consider the two matrices:
m1:
[[1 2 3]
 [4 5 6]]
m2:
[[ 6  7]
 [ 8  9]
 [10 11]]

Matrix multiplication
m1.shape: (2, 3)
m2.shape: (3, 2)
(2,3) x (3,2) => (2,2)

m1.dot(m2):
[[ 52  58]
 [124 139]]
m1 @ m2:
[[ 52  58]
 [124 139]]
m1.dot(m2).shape: (2, 2)

--------------------

Transpose of T
m1.T
[[1 4]
 [2 5]
 [3 6]]
m1.T.shape: (3, 2)


#### **Exercise**: Given a matrix M, how to compute M^T * M

In [19]:
# init the matrix 
print("Consider the matrix m:")
m = np.array([1,2,3,4,5,6]).reshape(2,3)
print(m)
print("m.shape:", m.shape)
print()

print("(3,2) x (2,3) => (3,3)")
print("m.T.dot(m):", m.T.dot(m)) # m^T * m
print("m.T.dot(m).shape:", m.T.dot(m).shape)


Consider the matrix m:
[[1 2 3]
 [4 5 6]]
m.shape: (2, 3)

(3,2) x (2,3) => (3,3)
m.T.dot(m): [[17 22 27]
 [22 29 36]
 [27 36 45]]
m.T.dot(m).shape: (3, 3)


### Broadcasting

Broadcast enables applying arithmetic operations on arrays of different shapes. When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way forward. Two dimensions are compatible when
1. they are equal, or
2. one of them is 1

For example, we can add a constant value to each element of a matrix.


In [20]:
print("Consider the given matrix m:")
m = np.array([[2,3,4,5], [3,4,5,6], [4,5,6,7]])
print(m)
print("m.shape:", m.shape)

print("\n-----------------\n")

print("Add 1 to every element of m")
print("m + 1:") # add 1 to each element of m
print(m + 1)
print()

print("Power of 2")
print("m ** 2:") # in Python, x**2 = x^2
print(m ** 2) 


Consider the given matrix m:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
m.shape: (3, 4)

-----------------

Add 1 to every element of m
m + 1:
[[3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]

Power of 2
m ** 2:
[[ 4  9 16 25]
 [ 9 16 25 36]
 [16 25 36 49]]


We can add a vector to each row/column of a matrix (if their sizes are valid). 

In [21]:
# suppose we want to add the vector to each row of the matrix m
v = np.array([1,2,3,4])
m = np.array([[2,3,4,5], [3,4,5,6], [4,5,6,7]])
print("Consider the vector v and the matrix m")
print("v:", v)
print("v.shape:", v.shape)
print()
print("m:")
print(m)
print("m.shape", m.shape)


print("\n-----------------\n")

print("Add v to each row of m by iteration:")
# by iteration
for row in m:
  row += v

print("m:")
print(m)

m = np.array([[2,3,4,5], [3,4,5,6], [4,5,6,7]]) # recover the values of m
print("\n-----------------\n")
# by broadcasting
print("Add v to each row of m by broadcasting:")
m += v
print("m += v")
print("m:")
print(m)




Consider the vector v and the matrix m
v: [1 2 3 4]
v.shape: (4,)

m:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
m.shape (3, 4)

-----------------

Add v to each row of m by iteration:
m:
[[ 3  5  7  9]
 [ 4  6  8 10]
 [ 5  7  9 11]]

-----------------

Add v to each row of m by broadcasting:
m += v
m:
[[ 3  5  7  9]
 [ 4  6  8 10]
 [ 5  7  9 11]]


#### **Exercise**: Add a vector to each column of a matrix

In [22]:
# init the vector and the matrix
v = np.array([1,2,3])
m = np.array([[2,3,4,5], [3,4,5,6], [4,5,6,7]])
print("Consider the vector v and the matrix m")
print("v:", v)
print("v.shape:", v.shape)
print()
print("m:")
print(m)
print("m.shape", m.shape)



print("\n-------------\n")

# m has shape (3,4) while v has shape (3,)
# we can transpose the matrix and apply the broadcast on each row, 
# then transpose back
# note: the transpose operation is cheap

print("Idea: add v to each row of the transpose of m")
print("m.T")
print(m.T)
print()


print("m.T + v")
print(m.T + v)
print()


print("m = (m.T + v).T:")
m = (m.T + v).T
print(m)




Consider the vector v and the matrix m
v: [1 2 3]
v.shape: (3,)

m:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
m.shape (3, 4)

-------------

Idea: add v to each row of the transpose of m
m.T
[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]

m.T + v
[[ 3  5  7]
 [ 4  6  8]
 [ 5  7  9]
 [ 6  8 10]]

m = (m.T + v).T:
[[ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]]


#### **Exercise**: Data normalization

Scale the data to a the range from 0 to 1


In [23]:
# init the matrix
m = np.random.random((5,4)) * 100
print("Consider the matrix m with random values from 0 to 100")
print(m)
print("m.shape", m.shape)

# A min-max scaling is typically done via the following equation:
# m_norm = (m - m_min) / (m_max - m_min)
# where m_min and m_max are the minimal and maximum values in m

print("\n-------------\n")

m_min = m.min() # np.min(m)
m_max = m.max() # np.max(m)
m_norm = (m - m_min) / (m_max - m_min)

print("Normalized m")
print(m_norm)
print("m_norm.shape", m_norm.shape)


Consider the matrix m with random values from 0 to 100
[[64.34731346 85.60708245 16.0225668  98.71510176]
 [14.66492365 36.49058662 35.48732478 34.83450828]
 [ 3.51749024 82.52332129 66.71195951 66.02578677]
 [71.61820506 71.3510499  69.26099357 72.68446362]
 [29.85580894  6.15446281  3.08787574 31.30825761]]
m.shape (5, 4)

-------------

Normalized m
[[0.64060666 0.86292586 0.13526159 1.        ]
 [0.12106435 0.34930126 0.33880988 0.3319832 ]
 [0.0044926  0.83067813 0.66533441 0.65815891]
 [0.71664036 0.71384664 0.69199035 0.72779051]
 [0.27991958 0.03206814 0.         0.29510823]]
m_norm.shape (5, 4)


#### **Exercise**: Column-wise data normalization

Can you do the data normalization column-wisely?